# 50 = CRITICAL
# 40 = ERROR
# 30 = WARNING
# 20 = INFO
# 10 = DEBUG
[LOGGING]
level = 20

[SERVER]
port = 2700
prefix = '/api'

[DATABASE]
dsn = ''

[OAUTH]
github_id = ""
github_secret = ""
redirect = ""